In [2]:
import pandas as pd
df = pd.read_csv("../../_Res_csv/IMDB-Movie-Data.csv")

In [4]:
df.head(2)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0

In [25]:
df[df.Title.str.contains(r"\bMan\b")]

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
78,79,Pirates of the Caribbean: Dead Man's Chest,"Action,Adventure,Fantasy",Jack Sparrow races to recover the heart of Dav...,Gore Verbinski,"Johnny Depp, Orlando Bloom, Keira Knightley, J...",2006,151,7.3,552027,423.03,53.0
104,105,The Man from U.N.C.L.E.,"Action,Adventure,Comedy","In the early 1960s, CIA agent Napoleon Solo an...",Guy Ritchie,"Henry Cavill, Armie Hammer, Alicia Vikander, E...",2015,116,7.3,202973,45.43,56.0
179,180,Ant-Man,"Action,Adventure,Comedy",Armed with a super-suit with the astonishing a...,Peyton Reed,"Paul Rudd, Michael Douglas, Corey Stoll, Evang...",2015,117,7.3,368912,180.19,64.0
203,204,Iron Man,"Action,Adventure,Sci-Fi","After being held captive in an Afghan cave, bi...",Jon Favreau,"Robert Downey Jr., Gwyneth Paltrow, Terrence H...",2008,126,7.9,737719,318.30,79.0
253,254,The Amazing Spider-Man 2,"Action,Adventure,Sci-Fi","When New York is put under siege by Oscorp, it...",Marc Webb,"Andrew Garfield, Emma Stone, Jamie Foxx, Paul ...",2014,142,6.7,342183,202.85,53.0
279,280,Iron Man Three,"Action,Adventure,Sci-Fi",When Tony Stark's world is torn apart by a for...,Shane Black,"Robert Downey Jr., Guy Pearce, Gwyneth Paltrow...",2013,130,7.2,591023,408.99,62.0
294,295,Man of Steel,"Action,Adventure,Fantasy","Clark Kent, one of the last of an extinguished...",Zack Snyder,"Henry Cavill, Amy Adams, Michael Shannon, Dian...",2013,143,7.1,577010,291.02,55.0
344,345,Spider-Man 3,"Action,Adventure",A strange black entity from another world bond...,Sam Raimi,"Tobey Maguire, Kirsten Dunst, Topher Grace, Th...",2007,139,6.2,406219,336.53,59.0
368,369,The Amazing Spider-Man,"Action,Adventure",After Peter Parker is bitten by a genetically ...,Marc Webb,"Andrew Garfield, Emma Stone, Rhys Ifans, Irrfa...",2012,136,7.0,474320,262.03,66.0
378,379,Swiss Army Man,"Adventure,Comedy,Drama",A hopeless man stranded on a deserted island b...,Dan Kwan,"Paul Dano, Daniel Radcliffe, Mary Elizabeth Wi...",2016,97,7.1,61812,4.21,64.0
450,451,Iron Man 2,"Action,Adventure,Sci-Fi",With the world now aware of his identity as Ir...,Jon Favreau,"Robert Downey Jr., Mickey Rourke, Gwyneth Palt...",2010,124,7.0,556666,312.06,57.0
593,594,She's the Man,"Comedy,Romance,Sport",When her brother decides to ditch for a couple...,Andy Fickman,"Amanda Bynes, Laura Ramsey, Channing Tatum,Vin...",2006,105,6.4,122864,2.34,45.0
779,780,The Man Who Knew Infinity,"Biography,Drama",The story of the life and academic career of t...,Matt Brown,"Dev Patel, Jeremy Irons, Malcolm Sinclair, Rag...",2015,108,7.2,29912,3.86,NaN
794,795,Man on a Ledge,"Action,Crime,Thriller",As a police psychologist works to talk down an...,Asger Leth,"Sam Worthington, Elizabeth Banks, Jamie Bell, ...",2012,102,6.6,129252,18.60,40.0
815,816,Inside Man,"Crime,Drama,Mystery","A police detective, a bank robber, and a high-...",Spike Lee,"Denzel Washington, Clive Owen, Jodie Foster,Ch...",2006,129,7.6,285441,88.50,76.0
824,825,Man Down,"Drama,Thriller","In a post-apocalyptic America, former U.S. Mar...",Dito Montiel,"Shia LaBeouf, Jai Courtney, Gary Oldman, Kate ...",2015,90,5.8,4779,NaN,27.0